### ISSUE TITLE
Error when token $value is negative value

### ISSUE THREAD

**Issue by mikeokijohn** [terrazzoapp/terrazzo#282]
Hello!

Thanks for the great work on implementing terrazzo :)

We are using it to transform our design tokens from Figma Variables to css variables, using the latest Figma API.
When running the `tz build` task, we encounter the following error for a token that has a "negative" $value:

<img width="839" alt="image" src="https://github.com/user-attachments/assets/b1cd555b-5143-4655-bb60-bd2f09ba2b9e">

The token looks like this, when delivered using the [TokensBrücke](https://github.com/tokens-bruecke/figma-plugin) Figma plugin:

```json
"neg-3": {
        "$type": "dimension",
        "$value": "-0.029999999329447746px",
        "$description": "letter-spacing: -3%",
        "$extensions": {
          "mode": {},
          "figma": {
            "variableId": "VariableID:2965:644",
            "collection": {
              "id": "VariableCollectionId:2963:612",
              "name": "Typography",
              "defaultModeId": "2963:0"
            }
          }
        }
      },
```

Is this error expected, so terrazzo is not able to handle tokens that has negative values?

FYI:

We are currently investigating moving from Cobalt to Terrazzo, so both projects are installed in our application. Should that be an issue?

Thanks again!

**Comment by drwpow** [comment]
Nope! This is a bug that should be fixed. Will fix and push a release later this week

**Comment by drwpow** [comment]
Fixed, and released! Sorry for the delay on this. Let me know if you’re still experiencing the issue!
