### ISSUE TITLE
Terrazzo not building json files into one token.json

### ISSUE THREAD

**Issue by mikeokijohn** [terrazzoapp/terrazzo#283]
Hi :)

We're migrating from Cobalt CLI to Terrazzo CLI, and trying to make the terrazzo config work correctly.

Currently we have an array of json files in the `tokens` property, and as the [docs](https://terrazzo.app/docs/cli/config/) say, this should be possible.
<img width="585" alt="image" src="https://github.com/user-attachments/assets/a1ff8691-12cf-4c09-897e-ad7abd4c5ef6">

But when building, we can see that the tokens we get are only the ones from the first json file.

It seems like the build step from Cobalt CLI is not 1:1 with Terrazzo, or are we doing something wrong? :)

**Comment by drwpow** [comment]
Oh that’s a bug; planned but not implemented yet. It has to do with the specific file + line error messages; just a bit more work is needed to handle multiple files and point to the correct file and line in case of an error. But is planned for stable release

**Comment by drwpow** [comment]
Started working on adding this! There are 3 medium-ish (not big, but not small) things left: multiple files, YAML support, and tokens linting, that are still TODO for the core CLI. So this will knock out 1/3 of what’s left (and of course, minor bugfixes, but bugfixes are a constant)

After that, it’s just updating the remaining plugins and Terrazzo should match all Cobalt can do and much more! 

Sidenote: my original plan was to get the functionality in Terrazzo stable, but not release the stable version until the DTCG spec was finalized later. But will adjust that as-needed (especially if the DTCG stable version is delayed). In either case, eager to hear your feedback on the beta once this feature is in!

**Comment by ramiejleh** [comment]
@drwpow thanks for the update! I'm on the same team as @mikeokijohn and working on implementing Terrazzo as well and looking forward for the beta to test it. For now, we have written our own bundling script just until Terrazzo has the support for it like Cobalt did.

I'd like to hear though if you know anything about the timeline for DTCG finalising and whether we know when we can expect a stable version?

**Comment by drwpow** [comment]
> For now, we have written our own bundling script just until Terrazzo has the support for it like Cobalt did.

That will work! The thing I was working on that’s taking a little more time is just keeping original filenames & line numbers in error reporting. It’s a minor thing, but just something I really wanted to have 🙂

> I'd like to hear though if you know anything about the timeline for DTCG finalising and whether we know when we can expect a stable version?

The original goal for the DTCG spec was end of year 2024. We are making progress! And I am doing what I can to attend the meetings and push it forward. Consensus is just slow, but it’s shaping toward a stable version. Also trying to improve communication and transparency so it’s clearer to everyone what the remaining roadmap is
