### ISSUE TITLE
Failing nested aliases type validation

### ISSUE THREAD

**Issue by nclsndr** [terrazzoapp/terrazzo#309]
The tokens parser is capable of catching type mismatches for scalar types but ignore the composites.

```ts
parse([{
  src: JSON.stringify({
    color: {
      $type: 'color',
      blue: {
        $value: '#10109A',
      },
    },
    dimension: {
      base: {
        $type: 'dimension',
        $value: '{color.blue}', // should be dimension: caught by parser ✅
      },
    },
    border: {
      base: {
        $type: 'border',
        $value: '{dimension.base}', // should be border: caught by parser ✅
      },
      nested: {
        $type: 'border',
        $value: {
          color: '{color.blue}',
          width: '{color.blue}', // should be dimension: silently failing ❌
          style: 'solid',
        },
      },
    },
  })
}])
```

I think that's not much of a deal, yet I preferred to report it while looking into it.

—
The only solution I found on my end was to manually declare [the mapping](https://github.com/nclsndr/design-tokens-tools/blob/main/packages/w3c-design-tokens-parser/src/definitions/TokenTypeAliasingCompatibility.ts).

**Comment by drwpow** [comment]
Ah that’s a great catch, thank you! Worth fixing for sure. I like your mapping approach; great suggestion.
