### ISSUE TITLE
Inset box shadow support

### ISSUE THREAD

**Issue by tomasfrancisco** [terrazzoapp/terrazzo#343]
Trying to setup inset shadows but couldn't find a way to add `inset` to a shadow, according to [DTCG format](https://arc.net/l/quote/ipxtuvgt). It seems though, there has been some sort of [reference](https://github.com/terrazzoapp/terrazzo/blob/be9603278f1a774233a13255c70811d0a0fe3058/packages/plugin-css/test/fixtures/type-shadow/tokens.json#L24) to it before.

Is it a missing property or is there other way we could flag an inset shadow?

**Comment by drwpow** [comment]
Oh we just recently changed that within the last month, so that’s new! But yes we need to add that to Terrazzo so that’s supported.

**Comment by tomasfrancisco** [comment]
I can pick on this one if you want. Let me know

**Comment by drwpow** [comment]
> I can pick on this one if you want. Let me know

Sure! Please do! As long as you start with tests in the parser, and make sure that those pass, that should be all that’s needed. Adding tests in the plugins are just a bonus (usually CSS gets most of the tests)
