### ISSUE TITLE
$extensions vendor proprietary keys get validated

### ISSUE THREAD

**Issue by tomasfrancisco** [terrazzoapp/terrazzo#363]
Ran into a warning where I believe is not intended?

```json
{
  "radius": {
    "xs": {
      "$type": "dimension",
      "$value": "4px",
      "$extensions": {
        "pro.getds": {
          "value": "4px"
        }
      }
    }
  }
}
```

Output:

```sh
Group radius.xs.$extensions.pro.getds has "value". Did you mean "$value"?
| 
|    6 |         "$value": "4px",
|    7 |         "$extensions": {
| >  8 |           "pro.getds": {
|      |           ^
|   9  |             "value": "4px"
|   10 |           }
```

[According to DTCG](https://arc.net/l/quote/oizmjxjp) - "each tool MUST use a vendor-specific key whose value MAY be any valid JSON data."

I'd think that if the `value` member is inside `$extensions`, it should not be validated so it would allow vendors to define any valid JSON format.

**Comment by drwpow** [comment]
Thanks for raising! Fixed in `0.2.5`
