### ISSUE TITLE
plugin-css: outdated dependencies

### ISSUE THREAD

**Issue by gynekolog** [terrazzoapp/terrazzo#382]
Current version plugin-css@0.1.2 reference to the @terrazzo/parser@0.1.3

The updates in @terrazzo/parser@2 are causing TypeScript errors in the plugin configuration.

Specifically, the default export from @terrazzo/plugin-css is typed as Plugin (based on @terrazzo/parser@0.1.3), but defineConfig from @terrazzo/parser@2 expects the newer Plugin type.

This type mismatch leads to compatibility issues.

ts error:
```
Types of parameters config and config are incompatible.
```

Temporary workaround is override typing:
```
import { defineConfig } from "@terrazzo/parser";
import type { Plugin } from "@terrazzo/parser";
import css from "@terrazzo/plugin-css";

export default defineConfig(
	{
		tokens: [
			"../tokens/foundations.exported.json",
			"../tokens/webapp.exported.json",
		],
		outDir: "../dist",
		plugins: [
			css({
				filename: "tokens.generated.css",
			}) as Plugin, // workaround, pending on updated @terrazzo/css
		],
	},
	{ cwd: new URL(import.meta.url) },
);
```

**Comment by drwpow** [comment]
Ah thank you for raising! Will bump all the plugins just for types. I was under the false impression they would just use the local types, but that doesn’t seem to be the case (I’ve seen similar things happen with Vite + Vite plugins)

**Comment by drwpow** [comment]
openapi-fetch and openapi-react-query got refreshes (you’ll have to update to the latest patch; for obvious reasons npm doesn’t let you re-publish a version), and confirmed the `dist/` folder was published correctly. Sorry for the inconvenience!

**Comment by drwpow** [comment]
Whoops; commented on the wrong issue here. I forgot that these packages do have `peerDependencies` of `@terrazzo/cli`, but also have a `dependency` of `@terrazzo/parser` which is where the type mismatch is in. Will also fix that!

**Comment by gynekolog** [comment]
Confirm it's solved. Thank you 🙏
