### ISSUE TITLE
npx tz build opens Cli.js

### ISSUE THREAD

**Issue by EwaDabrowskaAcn** [terrazzoapp/terrazzo#389]
I installed Terrazzo in the project. The configuration is ready. When running the **npx tz build** command, it does not return any error/progress information, does not process tokens. It only opens the Cli.js file every time. It was tested on different computers running different versions of Node.js.
I wonder if there is any known solution to this problem.

**Comment by drwpow** [comment]
Thanks for reporting. Is this installed locally, or globally? What version are you using?

**Comment by drwpow** [comment]
Happy to diagnose but I need either a reproduction of your code in a repo, or more information about your system. Closing for now but can reopen when I have more information. Note that we do run tests on Linux, macOS, and Windows in this repo that tests the build, so there may be something else going on.
